// GENERATED BY CODE! DO NOT MODIFY!
namespace Watermelon
{
	public partial class PrefsSettings
	{
		public enum Key
		{
			Vibration = 0,
			SoundVolume = 1,
			MusicVolumn = 2,
			Volume = 3,
		}
	}
}